# Welcome to Jekyll!

# Site settings
title: Yet Another Open Source Blog
email: epsi.nurwijayadi@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Learn and Discover Open Source with Daily Genuine Experience.
  From Coding, Design, Package Management Tweak to Desktop Customization.

# the subpath of your site, e.g. /blog
baseurl: "" 

# the base hostname & protocol for your site
url: "http://epsi-rns.github.io" 

# Missing timezone in metadata date can lead to wrong date in url
timezone: Asia/Jakarta

#opengraph
locale: en_US
logo: /assets/site/images/authors/epsi-vexel.png


paginate: 7
paginate_path: "pages/blog-:num"

# Build settings
markdown: kramdown

future: false

plugins:
   - jekyll-paginate
#  - jemoji

# External Services, leave blank to ignore or put true to use
# service:
# google_analytics_key: 
# yandex_metrica_key: 
# disqus_key: 
# muut: false
# google_adsense: 
   
comments: false
