# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet Another Open Source Blog
email: epsi.nurwijayadi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn and Discover Open Source with Daily Genuine Experience.
  From Coding, Design, Package Management Tweak to Desktop Customization.
baseurl: "" # the subpath of your site, e.g. /blog

# the base hostname & protocol for your site
url: "http://epsi-rns.github.io" 

# Missing timezone in metadata date can lead to wrong date in url
timezone: Asia/Jakarta

#opengraph
locale: en_US
logo: /assets/site/images/authors/epsi-vexel.png


paginate: 27
paginate_path: "pages/blog-:num"

# Build settings
markdown: kramdown

future: false

plugins:
   - jekyll-paginate
#  - jemoji

# External Services, leave blank to ignore or put true to use
# service:
# google_analytics_key: 
# yandex_metrica_key: 
# disqus_key: 
# muut: false
# google_adsense: 
   
comments: false
